version: "3.8"

services:
  app:
    image: pps:v3
    container_name: node_app
    restart: always

    env_file:
      - example.config.env
    environment:
      - DATABASE=mongodb://mongodb:27017/PricePointScout
      - REDIS_HOST=redis
      - NODE_ENV=production

    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6377:6379"
    networks:
      - app_network
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app_network

volumes:
  mongo_data:
  redis_data:

networks:
  app_network:
    driver: bridge
