apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-point-scout
  namespace: pps-namespace
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: price-point-scout
  template:
    metadata:
      labels:
        app: price-point-scout
    spec:
      restartPolicy: Always
      containers:
      - name: server
        image: omarzakaria10/price-point-scout:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "500Mi"
            cpu: "800m"
          limits:
            memory: "800Mi"
            cpu: "1600m"
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: pps-configmap
              key: NODE_ENV
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: pps-configmap
              key: REDIS_HOST
        - name: DATABASE
          valueFrom:
            configMapKeyRef:
              name: pps-configmap
              key: DATABASE
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: pps-configmap
              key: PORT
        - name: JWT_EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: pps-configmap
              key: JWT_EXPIRES_IN
        - name: JWT_COOKIE_EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: pps-configmap
              key: JWT_COOKIE_EXPIRES_IN
        - name: EMAIL_HOST
          valueFrom:
            configMapKeyRef:
              name: pps-configmap
              key: EMAIL_HOST
        - name: EMAIL_PORT
          valueFrom:
            configMapKeyRef:
              name: pps-configmap
              key: EMAIL_PORT
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pps-secret
              key: DATABASE_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: pps-secret
              key: JWT_SECRET
        - name: EMAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: pps-secret
              key: EMAIL_USERNAME
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pps-secret
              key: EMAIL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: price-point-scout-service  # Changed name to match ingress backend
  namespace: pps-namespace
spec:
  type: ClusterIP  # Changed from LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: price-point-scout
