apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: pps-namespace
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        resources:
          limits:
            memory: "200Mi"
            cpu: "100m"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: pps-namespace
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379

